#!/bin/bash

# ip-update
# 	(C) XENXIER 2015 - ALL RIGHTS ETC

# Self update
#git checkout master
#git pull origin master

# Get IP and checkout
git checkout ip
git pull origin ip

IP=curl 'https://wtfismyip.com/text'

# If the IP in the file is not our current IP
if [ "$(cat 'ip')" != "$($IP)"]; then
	# Save the new IP and current time
	curl "$($IP)" > ip
	date +%s > time

	# Update using Git
	git add ip
	git add time
	git commit -m 'Update IP'
	git push origin ip
fi
