#!/bin/bash

# ip-update
# 	(C) XENXIER 2015 - ALL RIGHTS ETC

# Self update
#git checkout master
#git pull origin master

cd /home/teamspeak/ip/

curl 'https://wtfismyip.com/text' > temp

# If the IP in the file is not our current IP
#if [ "$(cat ip)" != "$(cat temp)" ]; then
	# Save the new IP and current time
	rm ip
	mv temp ip
	date -I's' > time

	# Update using Git
	git add .
	git commit -m 'Update IP'
	git push origin ip
#fi

# Remove temp file
rm -rf temp
